### ISSUE TITLE
Could not extract JSON. Youtube API returned error 400 with message: "Request contains an invalid argument."

### ISSUE THREAD

**Issue by kendoodoo** [kevinf100/tuberepair.uptimetrackers.com#20]
They can't do this to us.

Hope it's just a code change from invidious, but I will make a direct innertube implementation while they're "fixing". And by "fixing", well, let's just say, tube.

Error:

![Screenshot 2024-11-07 at 17 49 42](https://github.com/user-attachments/assets/fa7c610c-a332-42d1-a5b0-f85c726a41c6)

**Comment by Preloading** [comment]
it's probably just down for a bit. things happen. if you really need it, just change the invidious url to one of the other public instances, or better, host your own.

**Comment by kendoodoo** [comment]
lol im the dev

**Comment by Preloading** [comment]
> lol im the dev

oh
