### ISSUE TITLE
Cant playing video

### ISSUE THREAD

**Issue by Kami-0x10** [kevinf100/tuberepair.uptimetrackers.com#31]
Im Japanese

Almost all videos cannot be played
Anyone else in the same situation?
I can read the comments and the summary of the video, but I can't play it

Specifically, even though I have specified the correct URL as shown in the picture, it redirects to the comment box after showing "Loading" as shown in the second picture.

![80cc080f3b380bde](https://github.com/user-attachments/assets/8634944d-fc40-4d1c-967a-1c696598943c)

![456bbad2ac41c4e2](https://github.com/user-attachments/assets/479948dc-7375-4c29-861a-73cf3dff5b75)

![5a014e5f7411be55](https://github.com/user-attachments/assets/9612931e-b0c0-4fce-940b-db05d11f01f4)

Environment: iPhone4s iOS6.1.3 (Jailbroken)
ISRG ROOT X1 profile installed
Installed TubeRepair

**Comment by kevinf100** [comment]
Was down due to YouTube changing how links work. The way we got links before was changed to be IP bound/locked :(
fixed with https://github.com/kevinf100/tuberepair.uptimetrackers.com/pull/32 for now.
